artifactory_database: "artifactory"
artifactory_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37303561393830636663616265646338356234393031323465643434326236303165383331613865
          6236326333316234613930663432393532343436666238330a633862323165636330303431303035
          39653237303233363338613866323134313336663138363065396266636637613861386434313131
          6332346265626432640a363562333532616465396262343262326333303930636466663863313465
          6264
artifactory_version: "6.0.1"
