---
dependencies: []

galaxy_info:
  author: Thomas Woerner, Victor da Costa
  description: Role with IPA modules
  company: Red Hat, Inc
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: Fedora
      versions:
        - 25
        - 26
        - 27
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - identity
    - ipa
